# Generated by Django 2.2.3 on 2019-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190721_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('mobileno', models.TextField()),
                ('gender', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
